language: node_js
services:
  - docker
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: false
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7.5'
before_script:
  - docker run -p 2181:2181 --name some-zookeeper --restart always -d zookeeper
  - npm prune && npm cache clean
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
